### ISSUE TITLE
Android studio 3.0 beta can't use generator 3.2.2

### ISSUE THREAD

**Issue by jeffreyliu8** [greenrobot/greenDAO#755]
Tried doing this on android studio 2.3.3, works just fine.
Brand new project(android studio 3.0 beta2), using gradle to compile the generator, would get 

Error:Execution failed for task ':lib:run'.
> Process 'command '/private/var/folders/7_/7gsmzg8x3m3835yx09cwx85h0000gs/T/AppTranslocation/57AF1295-3374-41DF-8BD8-FDD2034F5C81/d/Android Studio 3.0 Preview.app/Contents/jre/jdk/Contents/Home/bin/java'' finished with non-zero exit value 1

If use the play button to compile(a java library) it would give 

Exception in thread "main" java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema
	at com.askjeffreyliu.lib.myClass.main(myClass.java:16)
Caused by: java.lang.ClassNotFoundException: org.greenrobot.greendao.generator.Schema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

Process finished with exit code 1

**Comment by KyungminCho** [comment]
It looks like I have the same issue. I use Android Studio 3.0 beta2. 

objc[79443]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/bin/java (0x1079024c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_60.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x1079ca4e0). One of the two will be used. Which one is undefined.
Exception in thread "main" java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema
	at co.fronto.daogenerator.Generator.main(Generator.java:11)
Caused by: java.lang.ClassNotFoundException: org.greenrobot.greendao.generator.Schema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more

Process finished with exit code 1

**Comment by pablogupi** [comment]
I have the same issue. Please, could you give us some guidelines to repair it?

**Comment by pablogupi** [comment]
Solved!!
I update Android Studio to version 3.0.0 beta 5. 
After I added in Android Studio config Build,Execution,Deployment/Compiler/Command.line Options this line: --debug --stacktrace
When I executed gradle/application/run I viewed in stacktrace one error: Not found mainClassName.
 In the studio of Android look Main class in DaoGenerator package,  right button clicked/copy reference and paste in mainClassName in build.gradle. 

After executed gradle/application/run and viewed other error in this line:
        new DaoGenerator().generateAll(schema, "./app/src/main/java"); Path not exist.
Solved changing path like this:
        new DaoGenerator().generateAll(schema, "../app/src/main/java"); Path not exist.
When I  executed last gradle/application/run, GreenDao generated new tables without error. 

This is my DaoGenerator build.gradle:

`apply plugin: 'java'
apply plugin: 'application'

mainClassName = "com.*****.daogenerator.DAoGenerator"
sourceCompatibility = 1.8

dependencies {
    compile fileTree(dir: 'libs',include: ['*.jar'])
    compile 'org.greenrobot:greendao-generator:3.2.2'
}
`

References:
https://github.com/greenrobot/greenDAO/blob/V2.2.1/DaoExampleGenerator/src/de/greenrobot/daogenerator/gentest/ExampleDaoGenerator.java
https://github.com/greenrobot/greenDAO/issues/619
http://greenrobot.org/greendao/documentation/updating-to-greendao-3-and-annotations/
https://stackoverflow.com/a/37356322/2183365

**Comment by jeffreyliu8** [comment]
Changing from 2 dots to 2 dot worked for me. Thank you.

**Comment by greenrobot-team** [comment]
So the issue is just that paths are resolved differently? Closing this then. -ut

**Comment by martatenes** [comment]
Hello,
I am having the same issue and I after doing your approach still no luck. I am using android studio 3.0 

Exception when I run the generator
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/greenrobot/greendao/generator/Schema
	at com.greendao.MyGenerator.main(MyGenerator.java:11)
Caused by: java.lang.ClassNotFoundException: org.greenrobot.greendao.generator.Schema
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
```
`
```
public class MyGenerator {

    public static void main(String[] args) throws Exception {
        try {
            Schema schema = new Schema(1, "com.pixelcom.beta.pixelkartingsocios.models");

            Entity note = schema.addEntity("Note");
            note.addIdProperty();
            note.addStringProperty("text").notNull();
            note.addStringProperty("comment");
            note.addDateProperty("date");

            new DaoGenerator().generateAll(schema, "../app/src/main/java");
        }
        catch(Exception e){
            e.printStackTrace();
        }
    }
}
```

**greenDaoGenerator** build.gradle
```
apply plugin: 'java-library'
apply plugin: 'application'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    compile 'org.greenrobot:greendao-generator:3.2.2'
}

mainClassName="com.greendao.MyGenerator"
sourceCompatibility = "1.8"
targetCompatibility = "1.8"
```

**app** build.gradle
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'org.greenrobot.greendao'

android {
    buildToolsVersion '26.0.2'
    compileSdkVersion 26

    defaultConfig {
        applicationId "com.pixelcom.beta.pixelkartingsocios"
        minSdkVersion 15
        targetSdkVersion 26
        versionCode 1
        versionName "3"

        testInstrumentationRunner "android.test.InstrumentationTestRunner"
    }
}

greendao {
    schemaVersion 1000
}

dependencies {
    implementation fileTree(include: ['*.jar'], dir: 'libs')
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'org.greenrobot:greendao:3.2.2'
    compile 'com.android.support:appcompat-v7:26.1.0'
    compile 'com.android.support:recyclerview-v7:26.1.0'
}

uploadArchives.enabled = false
```


**project** buid.gradle

```
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    
    repositories {
        google()
        jcenter()
        mavenCentral();
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.0'
        classpath 'org.greenrobot:greendao-gradle-plugin:3.2.2' // add plugin


        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

```

Please help! :(
